# Generated by Django 2.1.1 on 2018-09-12 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=30)),
                ('FechaCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Costo', models.IntegerField()),
                ('Disponibilidad', models.BooleanField(default=True)),
                ('Existencias', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Categoria')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto')),
            ],
        ),
    ]
